# Generated by Django 4.0.2 on 2022-03-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='name',
            field=models.CharField(max_length=60, verbose_name='file name'),
        ),
    ]
