# Generated by Django 4.0.2 on 2022-04-10 13:26

import coffee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_menu_remove_testimonial_image_orderbooking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, validators=[coffee.models.email_validator]),
        ),
    ]
